# **Dataset Cleaning**
# Table of contents
1. [Import data](#step1) <br>
    1.1 [Read the first and last rows](#step1.1)
2. [Merge datasets](#step2)
3. [Show a concise summary of the datasets](#step3)
4. [Check the unique values of the columns](#step4)
5. [Rebuild missing data](#step5)
6. [De-Duplicate data](#step6)
7. [Cleaning text columns](#step7)
8. [Export datasets](#step8)

In [1]:
import re
import calendar
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

## **1. Import data** <a name="step1"></a>

##### **A. The global information dataframe**

In [2]:
dfGeneral= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/generalInfoAirlines.csv',index_col= 0)

##### **B. The airlines dataframes**

In [3]:
saudia_df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/saudia_airlines_reviews2.csv',index_col= 0)
etihad_df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/etihad_airways_reviews2.csv',index_col= 0)
turkish_df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/turkish_airlines_reviews2.csv',index_col= 0)
qatar_df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/qatar_airways_reviews2.csv',index_col= 0)
emirates_df= pd.read_csv('/content/drive/MyDrive/Colab Notebooks/emirates_reviews2.csv',index_col= 0)

### **1.1 Read the first and last rows** <a name="step1.1"></a>

##### **A. The global information dataframe**

In [4]:
dfGeneral.head()

,airline_name,rating,reviews,travelers_choice_winner,Legroom,Seat comfort,"In-flight entertainment (WiFi, TV, movies)",Onboard Experience,Customer service,Value for money,Cleanliness,Check-in and boarding,Food and beverage
0,saudia_airlines,3.0,"3,695 reviews","[""Travelers' Choice 2018 Winner""]",3.5,3.5,3.0,3.5,3.5,3.5,3.5,3.5,3.5
1,turkish_airlines,3.5,"34,447 reviews","[""Travelers' Choice 2019 Winner"", ""Travelers' ...",3.5,3.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0
2,qatar_airways,4.0,"34,682 reviews","[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.0,4.0,4.0,4.0,4.5,4.0,4.0
3,etihad_airways,3.0,"18,247 reviews","[""Travelers' Choice 2018 Winner"", ""Travelers' ...",3.5,3.5,3.5,3.5,3.5,3.5,4.0,3.5,3.5
4,emirates,4.0,"64,105 reviews","[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.5,4.0,4.0,4.0,4.5,4.5,4.0

In [5]:
dfGeneral.tail()

,airline_name,rating,reviews,travelers_choice_winner,Legroom,Seat comfort,"In-flight entertainment (WiFi, TV, movies)",Onboard Experience,Customer service,Value for money,Cleanliness,Check-in and boarding,Food and beverage
0,saudia_airlines,3.0,"3,695 reviews","[""Travelers' Choice 2018 Winner""]",3.5,3.5,3.0,3.5,3.5,3.5,3.5,3.5,3.5
1,turkish_airlines,3.5,"34,447 reviews","[""Travelers' Choice 2019 Winner"", ""Travelers' ...",3.5,3.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0
2,qatar_airways,4.0,"34,682 reviews","[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.0,4.0,4.0,4.0,4.5,4.0,4.0
3,etihad_airways,3.0,"18,247 reviews","[""Travelers' Choice 2018 Winner"", ""Travelers' ...",3.5,3.5,3.5,3.5,3.5,3.5,4.0,3.5,3.5
4,emirates,4.0,"64,105 reviews","[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.5,4.0,4.0,4.0,4.5,4.5,4.0

##### **B. The airlines dataframes**

In [6]:
saudia_df.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,saudia_airlines,If you have no other choice or are on a limite...,Probably the worst airline I have ever flown w...,"October 6, 2023",1,Date of travel: September 2023,3,1,3,1,3,1,2,1
1,saudia_airlines,DO NOT FLY SAUDIA,"unreliable, keeps changing flight times and da...","October 5, 2023",2,Date of travel: October 2023,0,0,0,0,0,0,0,0
2,saudia_airlines,You are fare from Saudi vision 2030,The service on board is perfect. The problem i...,"October 2, 2023",1,Date of travel: August 2023,0,0,0,0,0,0,0,0
3,saudia_airlines,Worst customer service,"Flight Number SV551, from JED to DXB. I would ...","October 2, 2023",1,Date of travel: October 2023,0,1,0,0,0,0,0,1
4,saudia_airlines,Dissatisfaction and unprofessionalism from Sau...,I am writing this about my experience regardin...,"September 30, 2023",1,Date of travel: August 2023,1,1,1,0,1,1,1,1

In [7]:
saudia_df.tail()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
2130,saudia_airlines,Crap crew,my 4months old baby had a bassinet prebooked (...,"January 29, 2016",1,Date of travel: December 2015,2,1,0,0,2,1,1,0
2131,saudia_airlines,NEVER AGAIN,I just can't believe an international airlines...,"January 26, 2016",1,Date of travel: December 2015,1,2,0,0,3,1,1,0
2132,saudia_airlines,NaN,NaN,"October 10, 2023",4,Date of travel: September 2023,0,0,0,0,0,0,0,0
2133,saudia_airlines,NaN,NaN,"October 10, 2023",1,Date of travel: September 2023,3,1,1,2,2,2,1,1
2134,saudia_airlines,NaN,NaN,"October 1, 2023",1,Date of travel: September 2023,3,2,5,0,4,4,3,3

In [8]:
etihad_df.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,etihad_airways,Stop Over on Us program is marketing hype with...,I deliberately scheduled a flight to have a lo...,"October 3, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
1,etihad_airways,An Overhyped Terrible Airline,I contacted their customer care to resolve an ...,"October 3, 2023",1,Date of travel: September 2023,1,1,2,2,1,2,1,2
2,etihad_airways,Avoid this airline,Pay for upgrade. Get money withdrawn from acco...,"October 3, 2023",1,Date of travel: October 2023,2,1,2,3,2,1,0,1
3,etihad_airways,Sad Etihad,Disappointed with plane offered on this flight...,"October 2, 2023",3,Date of travel: August 2023,1,3,1,2,1,1,1,3
4,etihad_airways,Still waiting for refund!,"After 7 phone calls, no one seems to know what...","October 2, 2023",1,Date of travel: May 2023,0,0,0,0,0,0,0,0

In [9]:
etihad_df.tail()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
13120,etihad_airways,NaN,NaN,"September 28, 2023",2,Date of travel: September 2023,3,5,3,3,3,4,1,5
13121,etihad_airways,NaN,NaN,"September 28, 2023",1,Date of travel: August 2023,1,2,2,2,1,2,1,1
13122,etihad_airways,NaN,NaN,"September 25, 2023",3,Date of travel: September 2023,0,0,0,0,0,0,0,0
13123,etihad_airways,NaN,NaN,"September 25, 2023",1,Date of travel: September 2023,1,3,3,3,1,5,1,5
13124,etihad_airways,NaN,NaN,"September 23, 2023",1,Date of travel: January 2023,2,2,2,2,2,2,2,2

In [10]:
turkish_df.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,turkish_airlines,Terrible Airline,"terrible service, seats were not clean, flight...","October 5, 2023",1,Date of travel: May 2023,1,1,1,1,1,1,1,1
1,turkish_airlines,A very pleasant air travel experience!,My recent roundtrip flights from Boston to Kil...,"October 5, 2023",5,Date of travel: September 2023,4,5,5,5,4,4,5,5
2,turkish_airlines,"Never, Never Use Turkish Airlines Economy Class",I can't speak to Turkish Airlines' business cl...,"October 5, 2023",1,Date of travel: January 2023,1,1,3,1,1,3,1,0
3,turkish_airlines,"rude and miserable, horrible treatment","they are horrible at customer service, they de...","October 5, 2023",1,Date of travel: September 2023,1,1,1,1,1,1,1,1
4,turkish_airlines,Thankfully a better experience than some other...,I was reluctant to fly Turkish airlines due to...,"October 5, 2023",4,Date of travel: September 2023,5,3,4,4,5,5,4,4

In [11]:
turkish_df.tail()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
18165,turkish_airlines,NaN,NaN,"October 6, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
18166,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: September 2023,0,1,0,0,0,0,1,1
18167,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: August 2023,1,1,1,1,1,1,1,1
18168,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
18169,turkish_airlines,NaN,NaN,"October 4, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0

In [12]:
qatar_df.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,qatar_airways,Clean and brand new plane seat,Nice short flight. The plane was a brand new B...,"October 6, 2023",4,Date of travel: October 2023,5,4,5,5,5,0,4,3
1,qatar_airways,Very bad experience,I don't know why Qatar airways is considered o...,"October 6, 2023",2,Date of travel: September 2023,1,2,3,2,1,1,1,2
2,qatar_airways,QATAR AIRWAYS = A PLEASANT EXPERIENCE,I am a frequent airline traveler. For my work ...,"October 6, 2023",5,Date of travel: October 2023,5,5,5,5,5,5,5,5
3,qatar_airways,Joke of an airline,Qatar Airways are a joke. Ryanair are better t...,"October 6, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
4,qatar_airways,Excellent QR1336 and QR 709,Compliments first....i was suggested by a frie...,"October 6, 2023",4,Date of travel: October 2023,4,4,4,4,4,4,4,4

In [13]:
qatar_df.tail()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
23050,qatar_airways,NaN,NaN,"October 4, 2023",3,Date of travel: September 2023,3,4,5,3,3,4,3,5
23051,qatar_airways,NaN,NaN,"October 3, 2023",4,Date of travel: September 2023,4,4,4,3,4,5,4,4
23052,qatar_airways,NaN,NaN,"October 2, 2023",1,Date of travel: September 2023,0,0,0,0,0,0,0,0
23053,qatar_airways,NaN,NaN,"October 2, 2023",1,Date of travel: August 2023,0,0,0,0,0,0,0,0
23054,qatar_airways,NaN,NaN,"September 30, 2023",5,Date of travel: September 2023,5,5,5,5,5,5,5,5

In [14]:
emirates_df.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,emirates,Disappointing Experience with Emirates Custome...,My recent flight with Emirates from Dubai to B...,"October 5, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
1,emirates,Why pay for a seat on already expensive ticket...,It used to be a airline that understood servic...,"October 4, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
2,emirates,Another good flight with Emirates,Recently flew with Emirates from Hong Kong to ...,"October 4, 2023",4,Date of travel: August 2023,4,3,3,3,5,4,4,4
3,emirates,Wheelchair passangers,I just wanted to inform you an incident and co...,"October 4, 2023",1,Date of travel: September 2023,3,1,4,2,3,3,2,3
4,emirates,Bad service complaint,One of my friend travelled through emirates. A...,"October 4, 2023",2,Date of travel: September 2023,0,0,0,0,0,0,0,0

In [15]:
emirates_df.tail()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
41915,emirates,NaN,NaN,"October 4, 2023",1,Date of travel: October 2023,1,1,1,1,1,3,1,1
41916,emirates,NaN,NaN,"October 2, 2023",1,Date of travel: September 2023,1,1,2,1,2,1,1,1
41917,emirates,NaN,NaN,"October 1, 2023",3,Date of travel: October 2023,2,5,4,1,1,1,3,5
41918,emirates,NaN,NaN,"October 1, 2023",1,Date of travel: September 2023,2,1,3,1,3,4,2,4
41919,emirates,NaN,NaN,"September 29, 2023",5,Date of travel: August 2023,5,5,5,5,5,4,4,5

## **2. Merge datasets** <a name="step2"></a>

This phase is for concatenating all airline dataframes into a single dataframe to create one airline dataset, not for the general dataframe.

In [16]:
df_all= pd.concat([saudia_df, etihad_df,turkish_df,qatar_df,emirates_df], ignore_index=True, sort=False)
df_all.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,saudia_airlines,If you have no other choice or are on a limite...,Probably the worst airline I have ever flown w...,"October 6, 2023",1,Date of travel: September 2023,3,1,3,1,3,1,2,1
1,saudia_airlines,DO NOT FLY SAUDIA,"unreliable, keeps changing flight times and da...","October 5, 2023",2,Date of travel: October 2023,0,0,0,0,0,0,0,0
2,saudia_airlines,You are fare from Saudi vision 2030,The service on board is perfect. The problem i...,"October 2, 2023",1,Date of travel: August 2023,0,0,0,0,0,0,0,0
3,saudia_airlines,Worst customer service,"Flight Number SV551, from JED to DXB. I would ...","October 2, 2023",1,Date of travel: October 2023,0,1,0,0,0,0,0,1
4,saudia_airlines,Dissatisfaction and unprofessionalism from Sau...,I am writing this about my experience regardin...,"September 30, 2023",1,Date of travel: August 2023,1,1,1,0,1,1,1,1

## **3. Show a concise summary of the datasets** <a name="step3"></a>

##### **A. The global information dataframe**

In [17]:
dfGeneral.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5 entries, 0 to 4
Data columns (total 13 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   airline_name                                5 non-null      object
 1   rating                                      5 non-null      float64
 2   reviews                                     5 non-null      object
 3   travelers_choice_winner                     5 non-null      object
 4   Legroom                                     5 non-null      float64
 5   Seat comfort                                5 non-null      float64
 6   In-flight entertainment (WiFi, TV, movies)  5 non-null      float64
 7   Onboard Experience                          5 non-null      float64
 8   Customer service                            5 non-null      float64
 9   Value for money                             5 non-null      float64
 10  Cleanliness                                 5 non-null      float64
 11  Check-in and boarding                       5 non-null      float64
 12  Food and beverage                           5 non-null      float64
dtypes: float64(10), object(3)
memory usage: 560.0+ bytes

##### **B. The airlines dataframe**

In [18]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 98405 entries, 0 to 98404
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   airline_name             98405 non-null  object
 1   review_title             98374 non-null  object
 2   review_description       98375 non-null  object
 3   review_date              98405 non-null  object
 4   rating_stars             98405 non-null  int64
 5   travel_date              98375 non-null  object
 6   Seat comfort             98405 non-null  int64
 7   Customer service         98405 non-null  int64
 8   Cleanliness              98405 non-null  int64
 9   Food and Beverage        98405 non-null  int64
 10  Legroom                  98405 non-null  int64
 11  In-flight Entertainment  98405 non-null  int64
 12  Value for money          98405 non-null  int64
 13  Check-in and boarding    98405 non-null  int64
dtypes: int64(9), object(5)
memory usage: 10.5+ MB

## **4.  Check the unique values of the columns** <a name="step4"></a>

#### **A. The airlines dataframe**

In [19]:
#check unique values of airline_name and integer columns
int_columns= ['airline_name','rating_stars','Seat comfort','Customer service', 'Value for money','Check-in and boarding',
              'Cleanliness','Food and Beverage', 'Legroom','In-flight Entertainment']
for col in int_columns:
    print('unique values of ', col,' column are:', df_all[col].unique())

unique values of  airline_name  column are: ['saudia_airlines' 'etihad_airways' 'turkish_airlines' 'qatar_airways'
 'emirates']
unique values of  rating_stars  column are: [1 2 5 3 4]
unique values of  Seat comfort  column are: [3 0 1 5 2 4]
unique values of  Customer service  column are: [1 0 2 5 4 3]
unique values of  Value for money  column are: [2 0 1 5 4 3]
unique values of  Check-in and boarding  column are: [1 0 4 5 2 3]
unique values of  Cleanliness  column are: [3 0 1 2 4 5]
unique values of  Food and Beverage  column are: [1 0 2 5 4 3]
unique values of  Legroom  column are: [3 0 1 2 5 4]
unique values of  In-flight Entertainment  column are: [1 0 5 3 2 4]

**There are no errors in the data; zero here is the default value, which means there are no ratings; ratings range from 1 to 5.**

## **5. Rebuild missing data** <a name="step5"></a>

#### **A. The global information dataframe**

In [20]:
dfGeneral.isna().any()

airline_name                                  False
rating                                        False
reviews                                       False
travelers_choice_winner                       False
Legroom                                       False
Seat comfort                                  False
In-flight entertainment (WiFi, TV, movies)    False
Onboard Experience                            False
Customer service                              False
Value for money                               False
Cleanliness                                   False
Check-in and boarding                         False
Food and beverage                             False
dtype: bool

#### **B. The airlines dataframe**

In [21]:
df_all.isna().any()

airline_name               False
review_title                True
review_description          True
review_date                False
rating_stars               False
travel_date                 True
Seat comfort               False
Customer service           False
Cleanliness                False
Food and Beverage          False
Legroom                    False
In-flight Entertainment    False
Value for money            False
Check-in and boarding      False
dtype: bool

**The review_title, review_description, and travel_date columns have some missing data; let's look at the missing rows and figure out how to deal with them.**

In [22]:
pd.set_option('display.max_rows', None)
df_all[df_all.isnull().any(axis=1)]

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
2132,saudia_airlines,NaN,NaN,"October 10, 2023",4,Date of travel: September 2023,0,0,0,0,0,0,0,0
2133,saudia_airlines,NaN,NaN,"October 10, 2023",1,Date of travel: September 2023,3,1,1,2,2,2,1,1
2134,saudia_airlines,NaN,NaN,"October 1, 2023",1,Date of travel: September 2023,3,2,5,0,4,4,3,3
3491,etihad_airways,"Fraudulent company, Does not deliver what they...",Me and my wife booked a flight with baggage fr...,"May 17, 2021",1,NaN,0,0,0,0,0,0,0,0
15251,etihad_airways,Flying to New York from Australia with Etihad ...,"My family and I recently flew from Perth, West...","September 12, 2015",1,NaN,0,0,0,0,0,0,0,0
15252,etihad_airways,NaN,NaN,"October 11, 2023",1,Date of travel: September 2023,1,1,1,1,1,1,1,1
15253,etihad_airways,NaN,NaN,"October 9, 2023",2,Date of travel: September 2023,0,0,0,0,0,0,0,0
15254,etihad_airways,NaN,NaN,"October 9, 2023",1,Date of travel: September 2023,1,4,4,3,1,3,1,1
15255,etihad_airways,NaN,NaN,"September 28, 2023",2,Date of travel: September 2023,3,5,3,3,3,4,1,5
15256,etihad_airways,NaN,NaN,"September 28, 2023",1,Date of travel: August 2023,1,2,2,2,1,2,1,1
15257,etihad_airways,NaN,NaN,"September 25, 2023",3,Date of travel: September 2023,0,0,0,0,0,0,0,0
15258,etihad_airways,NaN,NaN,"September 25, 2023",1,Date of travel: September 2023,1,3,3,3,1,5,1,5
15259,etihad_airways,NaN,NaN,"September 23, 2023",1,Date of travel: January 2023,2,2,2,2,2,2,2,2
15267,turkish_airlines,Turkish Airlines worse on punctuality,Two years in a row Turkish airlines delayed by...,"October 4, 2023",1,NaN,0,0,0,0,0,0,0,0
15328,turkish_airlines,Turkish Airlines Missed Connection Flights,"I travelled to Pakistan via Turkish Airlines, ...","September 22, 2023",1,NaN,0,0,0,0,0,0,0,0
16852,turkish_airlines,NaN,The TA lost my luggage and for the 5th day I a...,"August 7, 2022",1,Date of travel: August 2022,0,0,0,0,0,0,0,0
27139,turkish_airlines,TURKISH AIRLINES - Business Class,"Journey started in the gorgeous CIP Lounge, it...","March 14, 2018",5,NaN,0,0,0,0,0,0,0,0
29181,turkish_airlines,Turkish Airlines,I flew form İstanbul to Chicago by Turkish Air...,"August 29, 2017",5,NaN,0,0,0,0,0,0,0,0
33206,turkish_airlines,R,"Turkish airline customer service, the worst ex...","March 5, 2016",1,NaN,0,0,0,0,0,0,0,0
33425,turkish_airlines,NaN,NaN,"October 6, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
33426,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: September 2023,0,1,0,0,0,0,1,1
33427,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: August 2023,1,1,1,1,1,1,1,1
33428,turkish_airlines,NaN,NaN,"October 5, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
33429,turkish_airlines,NaN,NaN,"October 4, 2023",1,Date of travel: October 2023,0,0,0,0,0,0,0,0
33628,qatar_airways,AVOID QATAR AIRWAYS AT ANY COST!!!!!!!!!!!!!!!,My son and I were heading back home to New Yor...,"August 19, 2023",1,NaN,0,0,0,0,0,0,0,0
34957,qatar_airways,Visit Finland. Lost baggage,This is day 50 and counting after I checked-in...,"August 18, 2022",1,NaN,0,0,0,0,0,0,0,0
35060,qatar_airways,Qatar Airways is terrible,"Will never ever fly Qatar again, worse service...","July 29, 2022",1,NaN,0,0,0,0,0,0,0,0
35873,qatar_airways,Qatar Airways staff and performance at Manches...,"Avoid qatar Airways like a plague, just had a ...","December 10, 2021",1,NaN,0,0,0,0,0,0,0,0
36060,qatar_airways,Shame on Qatar Airway!,My travel route was planned as YUL- DOH via Qa...,"September 16, 2021",1,NaN,0,0,0,0,0,0,0,0
38621,qatar_airways,London to Singapore and return with quatar air...,"Hi all, just a brief note about a recent fligh...","December 9, 2019",5,NaN,0,0,0,0,0,0,0,0
41628,qatar_airways,Dr,Propmt airline service was good so was the foo...,"May 11, 2019",4,NaN,0,0,0,0,0,0,0,0
48472,qatar_airways,Al-Maha Services,My wife and I just returned to NY from Bangkok...,"February 25, 2018",5,NaN,0,0,0,0,0,0,0,0
49254,qatar_airways,Worst Experience in Business Class,The worst experience while traveling in busine...,"December 22, 2017",1,NaN,0,0,0,0,0,0,0,0
52181,qatar_airways,Qatar airlines,"My luggage missed one wheel, after some e-mail...","June 2, 2017",5,NaN,0,0,0,0,0,0,0,0
56101,qatar_airways,Best Airline 2015 must be a joke,Was flying from Singapore to Milan on 6th of A...,"April 7, 2016",1,NaN,0,0,0,0,0,0,0,0
56478,qatar_airways,NaN,NaN,"October 11, 2023",1,Date of travel: October 2023,1,1,1,1,1,1,1,1
56479,qatar_airways,NaN,NaN,"October 10, 2023",5,Date of travel: September 2023,5,4,4,5,5,4,3,4
56480,qatar_airways,NaN,NaN,"October 4, 2023",3,Date of travel: September 2023,3,4,5,3,3,4,3,5
56481,qatar_airways,NaN,NaN,"October 3, 2023",4,Date of travel: September 2023,4,4,4,3,4,5,4,4
56482,qatar_airways,NaN,NaN,"October 2, 2023",1,Date of travel: September 2023,0,0,0,0,0,0,0,0
56483,qatar_airways,NaN,NaN,"October 2, 2023",1,Date of travel: August 2023,0,0,0,0,0,0,0,0
56484,qatar_airways,NaN,NaN,"September 30, 2023",5,Date of travel: September 2023,5,5,5,5,5,5,5,5
56766,emirates,Bad service by Emirates cabin crew staff. I am...,While travelling from Dubai to Mumbai on EK 50...,"July 10, 2023",2,NaN,0,0,0,0,0,0,0,0
58324,emirates,Emirates cheated us by not providing the promi...,Emirates cheated us by not providing us with t...,"September 28, 2021",1,NaN,0,0,0,0,0,0,0,0
64287,emirates,"""Disappointing Emirates Forced Stop Over """,Disappointing stop over at the Crowne Plaza Du...,"July 30, 2019",1,NaN,0,0,0,0,0,0,0,0
71915,emirates,Good flight,"During my latest flight on Emirates, I have de...","November 4, 2018",5,NaN,0,0,0,0,0,0,0,0
79728,emirates,Our first Flight on Emirates planes,Well what can I say the whole experience was a...,"March 24, 2018",5,NaN,0,0,0,0,0,0,0,0
82006,emirates,Very high international standards,All Emirates' Business and First Class Lounges...,"January 9, 2018",5,NaN,0,0,0,0,0,0,0,0
86553,emirates,Only way to fly,I flew Business class from Perth to Amsterdam ...,"August 29, 2017",4,NaN,0,0,0,0,0,0,0,0
92951,emirates,Doctors,Myself dr p k Kuncheria and my better half dr ...,"September 28, 2016",3,NaN,0,0,0,0,0,0,0,0
93227,emirates,Food is very good .Seats service are very comf...,If you want a comfortable long flight to State...,"September 27, 2016",4,NaN,0,0,0,0,0,0,0,0
93281,emirates,Over charges,My wife and I are heading home from our trip t...,"September 27, 2016",1,NaN,0,0,0,0,0,0,0,0
93365,emirates,Emirates air lines,The best air lines all over the world welcomed...,"September 19, 2016",5,NaN,0,0,0,0,0,0,0,0
97855,emirates,Nice flight,I love emirets ...Venice to Dubai ....Dubai to...,"March 9, 2016",5,NaN,0,0,0,0,0,0,0,0
98398,emirates,NaN,NaN,"October 11, 2023",1,Date of travel: September 2023,4,1,1,2,4,4,2,3
98399,emirates,NaN,NaN,"October 11, 2023",3,Date of travel: August 2023,3,3,3,1,3,3,4,3
98400,emirates,NaN,NaN,"October 4, 2023",1,Date of travel: October 2023,1,1,1,1,1,3,1,1
98401,emirates,NaN,NaN,"October 2, 2023",1,Date of travel: September 2023,1,1,2,1,2,1,1,1
98402,emirates,NaN,NaN,"October 1, 2023",3,Date of travel: October 2023,2,5,4,1,1,1,3,5
98403,emirates,NaN,NaN,"October 1, 2023",1,Date of travel: September 2023,2,1,3,1,3,4,2,4
98404,emirates,NaN,NaN,"September 29, 2023",5,Date of travel: August 2023,5,5,5,5,5,4,4,5

**Because the review_title and review_description are the most important data in our dataset, we will delete all rows that do not contain this data.**

In [23]:
df_all= df_all.dropna(subset=['review_title', 'review_description'])

In [24]:
df_all.isna().sum()

airline_name                0
review_title                0
review_description          0
review_date                 0
rating_stars                0
travel_date                30
Seat comfort                0
Customer service            0
Cleanliness                 0
Food and Beverage           0
Legroom                     0
In-flight Entertainment     0
Value for money             0
Check-in and boarding       0
dtype: int64

**Now that only the travel_date column is missing data, we will fill it by review_date because it may be the same or more relevant to the travel_date.**

In [25]:
df_all.loc[(pd.isnull(df_all.travel_date)), 'travel_date'] = 'Date of travel: '+str(df_all['review_date'].str.split(' ')[0])+' '+str(df_all['review_date'].str.split(' ')[2])

In [26]:
df_all.head()

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,saudia_airlines,If you have no other choice or are on a limite...,Probably the worst airline I have ever flown w...,"October 6, 2023",1,Date of travel: September 2023,3,1,3,1,3,1,2,1
1,saudia_airlines,DO NOT FLY SAUDIA,"unreliable, keeps changing flight times and da...","October 5, 2023",2,Date of travel: October 2023,0,0,0,0,0,0,0,0
2,saudia_airlines,You are fare from Saudi vision 2030,The service on board is perfect. The problem i...,"October 2, 2023",1,Date of travel: August 2023,0,0,0,0,0,0,0,0
3,saudia_airlines,Worst customer service,"Flight Number SV551, from JED to DXB. I would ...","October 2, 2023",1,Date of travel: October 2023,0,1,0,0,0,0,0,1
4,saudia_airlines,Dissatisfaction and unprofessionalism from Sau...,I am writing this about my experience regardin...,"September 30, 2023",1,Date of travel: August 2023,1,1,1,0,1,1,1,1

In [27]:
df_all.isna().sum()

airline_name               0
review_title               0
review_description         0
review_date                0
rating_stars               0
travel_date                0
Seat comfort               0
Customer service           0
Cleanliness                0
Food and Beverage          0
Legroom                    0
In-flight Entertainment    0
Value for money            0
Check-in and boarding      0
dtype: int64

## **6. De-Duplicate data** <a name="step6"></a>

#### **A. The airlines dataframe**

In [28]:
df_all[df_all.duplicated()==True]

,airline_name,review_title,review_description,review_date,rating_stars,travel_date,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
13535,etihad_airways,Will never travel with this airline,I used some masked words and the review was re...,"September 7, 2016",1,Date of travel: July 2016,3,1,2,1,3,4,1,1
63650,emirates,Will definitely fly Emirates again,We flew from CHCH to London recently on Emirat...,"September 3, 2019",5,Date of travel: July 2019,4,4,5,4,5,5,5,5

**Drop duplicate rows**

In [29]:
df_all = df_all.drop_duplicates()

In [30]:
df_all[df_all.duplicated()==True]

Empty DataFrame
Columns: [airline_name, review_title, review_description, review_date, rating_stars, travel_date, Seat comfort, Customer service, Cleanliness, Food and Beverage, Legroom, In-flight Entertainment, Value for money, Check-in and boarding]
Index: []

## **7. Cleaning text columns** <a name="step7"></a>

#### **A. The global information dataframe**

Use airline_name column as the index

In [31]:
dfGeneral.set_index('airline_name', inplace=True)

Number of reviews column is a string column need to be converted to integer

In [32]:
dfGeneral['reviews'] = dfGeneral['reviews'].str.split(' ').str[0].str.replace(',', '').astype(float)
dfGeneral

,rating,reviews,travelers_choice_winner,Legroom,Seat comfort,"In-flight entertainment (WiFi, TV, movies)",Onboard Experience,Customer service,Value for money,Cleanliness,Check-in and boarding,Food and beverage
airline_name,,,,,,,,,,,,
saudia_airlines,3.0,3695.0,"[""Travelers' Choice 2018 Winner""]",3.5,3.5,3.0,3.5,3.5,3.5,3.5,3.5,3.5
turkish_airlines,3.5,34447.0,"[""Travelers' Choice 2019 Winner"", ""Travelers' ...",3.5,3.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0
qatar_airways,4.0,34682.0,"[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.0,4.0,4.0,4.0,4.5,4.0,4.0
etihad_airways,3.0,18247.0,"[""Travelers' Choice 2018 Winner"", ""Travelers' ...",3.5,3.5,3.5,3.5,3.5,3.5,4.0,3.5,3.5
emirates,4.0,64105.0,"[""Travelers' Choice 2020 Winner"", ""Travelers' ...",4.0,4.0,4.5,4.0,4.0,4.0,4.5,4.5,4.0

In [33]:
dfGeneral.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, saudia_airlines to emirates
Data columns (total 12 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   rating                                      5 non-null      float64
 1   reviews                                     5 non-null      float64
 2   travelers_choice_winner                     5 non-null      object
 3   Legroom                                     5 non-null      float64
 4   Seat comfort                                5 non-null      float64
 5   In-flight entertainment (WiFi, TV, movies)  5 non-null      float64
 6   Onboard Experience                          5 non-null      float64
 7   Customer service                            5 non-null      float64
 8   Value for money                             5 non-null      float64
 9   Cleanliness                                 5 non-null      float64
 10  Check-in and boarding                       5 non-null      float64
 11  Food and beverage                           5 non-null      float64
dtypes: float64(11), object(1)
memory usage: 520.0+ bytes

Rename the reviews column to reviews_number

In [34]:
dfGeneral.rename(columns={'reviews': 'reviews_number'}, inplace=True)
dfGeneral.columns

Index(['rating', 'reviews_number', 'travelers_choice_winner', 'Legroom',
       'Seat comfort', 'In-flight entertainment (WiFi, TV, movies)',
       'Onboard Experience', 'Customer service', 'Value for money',
       'Cleanliness', 'Check-in and boarding', 'Food and beverage'],
      dtype='object')

To easily create plots, extract the years from the text in travelers_choice_winner column

In [35]:
# convert list to string
dfGeneral['travelers_choice_winner']= dfGeneral['travelers_choice_winner'].astype(str).str.replace('\[|\]|\'', '')
# extract the years from the string
for index,item in dfGeneral.iterrows():
    dfGeneral['travelers_choice_winner'][index]=([int(s) for s in dfGeneral['travelers_choice_winner'][index].split() if s.isdigit()])

In [36]:
dfGeneral.head()

,rating,reviews_number,travelers_choice_winner,Legroom,Seat comfort,"In-flight entertainment (WiFi, TV, movies)",Onboard Experience,Customer service,Value for money,Cleanliness,Check-in and boarding,Food and beverage
airline_name,,,,,,,,,,,,
saudia_airlines,3.0,3695.0,[2018],3.5,3.5,3.0,3.5,3.5,3.5,3.5,3.5,3.5
turkish_airlines,3.5,34447.0,"[2019, 2018, 2017]",3.5,3.5,4.0,4.0,4.0,4.0,4.0,4.0,4.0
qatar_airways,4.0,34682.0,"[2020, 2019, 2018, 2017]",4.0,4.0,4.0,4.0,4.0,4.0,4.5,4.0,4.0
etihad_airways,3.0,18247.0,"[2018, 2017]",3.5,3.5,3.5,3.5,3.5,3.5,4.0,3.5,3.5
emirates,4.0,64105.0,"[2020, 2019, 2018, 2017]",4.0,4.0,4.5,4.0,4.0,4.0,4.5,4.5,4.0

#### **B. The airlines dataframe**

Extract year and month from the travel_date and review_date to add new column, this will allow us to do some trend analysis later.

In [37]:
temp_review= df_all['review_date']
df_all.insert(4, "review_month", temp_review.str.split(' ').str[0].str.strip())
df_all.insert(5, "review_year", temp_review.str.split(' ').str[2].str.strip())

In [38]:
# Check unique year and month values if contains not correct values
print('Unique year values of review_year column are: ', *df_all.review_year.unique(), sep = ', ')
print('Unique month values of review_year column are: ', *df_all.review_month.unique(), sep = ', ')

Unique year values of review_year column are: , 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015
Unique month values of review_year column are: , October, September, August, July, June, May, April, March, February, January, December, November

In [39]:
# conver month name to number
month_dict = dict((v, k) for k, v in enumerate(calendar.month_name))
df_all.review_month= df_all.review_month.map(month_dict)

In [40]:
df_all = df_all.drop('review_date', axis=1)

In [41]:
temp_travel= df_all['travel_date'].str.split(':').str[1].str.strip()
df_all.insert(7, "travel_month", temp_travel.str.split(' ').str[0].str.strip())
df_all.insert(8, "travel_year", temp_travel.str.split(' ').str[1].str.strip())

In [42]:
# Check unique year and month values if contains not correct values
print('Unique year values of travel_year column are: ', *df_all.travel_year.unique(), sep = ', ')
print('Unique month values of travel_month column are: ', *df_all.travel_month.unique(), sep = ', ')

Unique year values of travel_year column are: , 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015, '6,',, 2563, 2562, 2561
Unique month values of travel_month column are: , September, October, August, July, May, June, January, April, March, February, December, November, ['October',

**As we can see above, there are errors in both columns that need to be fixed. Error data in the year column will be replaced with the review_year value from the same row. The month column has an error, which is ['October,' which will be modified to October.**

In [43]:
df_all.loc[df_all['travel_month'] == "['October',", ['travel_month']]= 'October'

In [44]:
incor_years= ["'6,',", '2563', '2562', '2561']
#df_all.loc[df_all['travel_year'].isin(incor_years), ['travel_year']] = df_all['review_year']
for i in incor_years:
  df_all.loc[df_all['travel_year']==i, ['travel_year']] = df_all['review_year']

In [45]:
# conver month name to number
df_all.travel_month= df_all.travel_month.map(month_dict)

In [46]:
# Check again unique year and month values if contains not correct values
print('Unique year values of travel_year column are: ', *df_all.travel_year.unique(), sep = ', ')
print('Unique month values of travel_month column are: ', *df_all.travel_month.unique(), sep = ', ')

Unique year values of travel_year column are: , 2023, 2022, 2021, 2020, 2019, 2018, 2017, 2016, 2015
Unique month values of travel_month column are: , 9, 10, 8, 7, 5, 6, 1, 4, 3, 2, 12, 11

In [47]:
df_all = df_all.drop('travel_date', axis=1)

In [48]:
df_all.head()

,airline_name,review_title,review_description,review_month,review_year,rating_stars,travel_month,travel_year,Seat comfort,Customer service,Cleanliness,Food and Beverage,Legroom,In-flight Entertainment,Value for money,Check-in and boarding
0,saudia_airlines,If you have no other choice or are on a limite...,Probably the worst airline I have ever flown w...,10,2023,1,9,2023,3,1,3,1,3,1,2,1
1,saudia_airlines,DO NOT FLY SAUDIA,"unreliable, keeps changing flight times and da...",10,2023,2,10,2023,0,0,0,0,0,0,0,0
2,saudia_airlines,You are fare from Saudi vision 2030,The service on board is perfect. The problem i...,10,2023,1,8,2023,0,0,0,0,0,0,0,0
3,saudia_airlines,Worst customer service,"Flight Number SV551, from JED to DXB. I would ...",10,2023,1,10,2023,0,1,0,0,0,0,0,1
4,saudia_airlines,Dissatisfaction and unprofessionalism from Sau...,I am writing this about my experience regardin...,9,2023,1,8,2023,1,1,1,0,1,1,1,1

In [49]:
df_all.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 98372 entries, 0 to 98397
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   airline_name             98372 non-null  object
 1   review_title             98372 non-null  object
 2   review_description       98372 non-null  object
 3   review_month             98372 non-null  int64
 4   review_year              98372 non-null  object
 5   rating_stars             98372 non-null  int64
 6   travel_month             98372 non-null  int64
 7   travel_year              98372 non-null  object
 8   Seat comfort             98372 non-null  int64
 9   Customer service         98372 non-null  int64
 10  Cleanliness              98372 non-null  int64
 11  Food and Beverage        98372 non-null  int64
 12  Legroom                  98372 non-null  int64
 13  In-flight Entertainment  98372 non-null  int64
 14  Value for money          98372 non-null  int64
 15  Check-in and boarding    98372 non-null  int64
dtypes: int64(11), object(5)
memory usage: 14.8+ MB

In [50]:
df_all.travel_year.unique()

array(['2023', '2022', '2021', '2020', '2019', '2018', '2017', '2016',
       '2015'], dtype=object)

## **8. Export dataset** <a name="step8"></a>

#### **A. The global information dataframe**

In [51]:
dfGeneral.to_csv('/content/drive/MyDrive/Colab Notebooks/general_airlines_cleaned.csv')

#### **B. The airlines dataframe**

In [52]:
df_all.to_csv('/content/drive/MyDrive/Colab Notebooks/airlines_dataset.csv')